---


- name: "Place {{ item }} plugin"
  git:
    repo: "https://github.com/centosadmin/{{ item }}.git"
    dest: "/opt/redmine/redmine-{{ redmine_version }}/plugins/{{ item }}"
    update: no

- include: migrate_plugins.yml
