---

- name: Purge default site nginx configuration
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - /etc/nginx/sites-enabled/default
    - /etc/nginx/sites-available/default
  register: nginx_default

- name: Ensure html placeholder exist
  copy:
    src: redmine_error.html
    dest: "/opt/redmine/redmine-{{ redmine_version }}/redmine_error.html"

- name: Get info about current redmine site configuration
  stat:
    path: "/etc/nginx/sites-available/{{ domain }}"
  register: nginx_redmine_configuration

- name: Place nginx redmine configuration
  template:
    src: redmine.conf
    dest: "/etc/nginx/sites-available/{{ domain }}"
  register: nginx_redmine_configuration_placed
  when: nginx_redmine_configuration.stat.islnk is not defined

- name: Place symbolic link to redmine
  file:
    state: link
    src: "/etc/nginx/sites-available/{{ domain }}"
    dest: "/etc/nginx/sites-enabled/{{ domain }}"
  when: nginx_redmine_configuration.stat.islnk is not defined

- name: Reload nginx
  service:
    name: nginx
    state: reloaded
  when: nginx_redmine_configuration_placed.changed or nginx_default.changed
