---

- name: "Place {{ item }} systemd service"
  template:
    src: "{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"

- name: Reload systemd
  systemd:
    daemon_reload: yes
  changed_when: false
