#### Trouble with query
# - name: Install full-text search module
#   include: plugin_full_text_search.yml

#### Problems with ActiveRecord query, refactoring requed
# - name: "Place redmine_workload plugin"
#   git:
#     repo: https://github.com/JostBaron/redmine_workload.git
#     dest: "/opt/redmine/redmine-{{ redmine_version }}/plugins/redmine_workload"
#     update: no
#   register: plugin
# - include: migrate_plugins.yml
#   when: plugin.changed

#### Plugin breaking issues view
# - name: "Place redmine_close_button plugin"
#   git:
#     repo: https://github.com/Undev/redmine_close_button.git
#     dest: "/opt/redmine/redmine-{{ redmine_version }}/plugins/close_button"
#     update: no
#   register: plugin
# - include: migrate_plugins.yml
#   when: plugin.changed

# info: https://github.com/mikitex70/redmine_drawio
# info: https://github.com/danmunn/redmine_dmsf
# - name: "[LONG TASK] Proceed apt dependences for full support dmsf and draw.io plugin"
#   apt:
#     name: "{{ item }}"
#     state: installed
#   with_items:
#     - xapian-omega
#     - ruby-xapian
#     - xapian-omega
#     - libxapian-dev
#     - xpdf
#     - poppler-utils
#     - antiword
#     - unzip
#     - catdoc
#     - libwpd-tools
#     - libwps-tools
#     - gzip
#     - unrtf
#     - catdvi
#     - djview
#     - djview3
#     - uuid
#     - uuid-dev
#     - xz-utils
#     - libemail-outlook-message-perl
# 
# - name: "Place dmsf plugin"
#   git:
#     repo: https://github.com/danmunn/redmine_dmsf.git
#     dest: "/opt/redmine/redmine-{{ redmine_version }}/plugins/dmsf"
#     update: no
#   register: plugin
# - include: migrate_plugins.yml
#   when: plugin.changed
# 
# - name: "Place draw.io plugin"
#   git:
#     repo: https://github.com/mikitex70/redmine_drawio.git
#     dest: "/opt/redmine/redmine-{{ redmine_version }}/plugins/draw"
#     update: no
#   register: plugin
# - include: migrate_plugins.yml
#   when: plugin.changed

#### Not working
# - name: "Place impersonate plugin"
#   git:
#     repo: https://github.com/rgtk/redmine_impersonate.git
#     dest: "/opt/redmine/redmine-{{ redmine_version }}/plugins/impersonate"
#     update: no
#   register: plugin
# - include: migrate_plugins.yml
#   when: plugin.changed
# 
#### Breaking all views
# - name: "Place theme_changer plugin"
#   git:
#     repo: https://github.com/haru/redmine_theme_changer.git
#     dest: "/opt/redmine/redmine-{{ redmine_version }}/plugins/theme_changer"
#     update: no
#   register: plugin
# - include: migrate_plugins.yml
#   when: plugin.changed

#### debugging
# - file:
#     path: "{{ item }}"
#     state: absent
#   with_items:
#     - "/opt/redmine/redmine-{{ redmine_version }}/plugins/dmsf"
#     - "/opt/redmine/redmine-{{ redmine_version }}/plugins/draw"
#     - "/opt/redmine/redmine-{{ redmine_version }}/plugins/impersonate"
#     - "/opt/redmine/redmine-{{ redmine_version }}/plugins/theme_changer"
# - include: migrate_plugins.yml





# ---
# 
# - apt:
#     name: apt-transport-https
#     state: installed
# 
# - apt_repository:
#     repo: deb https://packages.groonga.org/debian/ stretch main
#     state: present
#   ignore_errors: true
# 
# - shell: apt-get update -qq
#   ignore_errors: true
# 
# - shell: apt-get install groonga-keyring -yq
#   ignore_errors: true
# 
# - apt:
#     update_cache: true
#     name: postgresql-9.6-pgroonga
#     state: installed
# 
# - shell: "psql --command 'CREATE EXTENSION pgroonga;' {{ redmine_db_name }}"
#   become: yes
#   become_user: postgres
#   ignore_errors: true
#   register: psql_ext
# 
# 
# - name: "Place full_text_search plugin"
#   git:
#     repo: https://github.com/okkez/redmine_full_text_search.git
#     dest: "/opt/redmine/redmine-{{ redmine_version }}/plugins/full_text_search"
#     update: no
#   register: plugin
# - include: migrate_plugins.yml
#   when: plugin.changed