---

- name: "Get info about theme {{ item }}"
  stat:
    path: "/opt/redmine/redmine-{{ redmine_version }}/public/themes/"
  register: theme

- name: "Install theme from {{ item }}"
  unarchive:
    src: "{{ item }}"
    dest: "/opt/redmine/redmine-{{ redmine_version }}/public/themes/"
    remote_src: yes
  when: theme.stat.islnk is not defined
